import type { CvDocument } from "@/lib/cv/schema";

/** Perfil maestro enriquecido de Andrés (seed user-local). */
export const ANDRES_CV_SEED: CvDocument = {
  basics: {
    fullName: "Andrés Felipe Bonett Maldonado",
    headline: "Desarrollador Frontend | React | Next.js | TypeScript",
    location: "Barranquilla, Colombia",
    phone: "+57 300 275 1775",
    email: "andresbonettm@gmail.com",
    availability: "Remoto, híbrido o presencial",
    links: {
      linkedin: "https://linkedin.com/in/andresbonett",
      github: "https://github.com/andresbonett",
      portfolio: "https://andresbonett.github.io",
    },
  },
  summary:
    "Desarrollador Frontend con más de 5 años de experiencia desarrollando aplicaciones web modernas con React, Next.js y TypeScript. Experiencia en desarrollo móvil con React Native, gestión de estado con Zustand, Redux Toolkit y React Context, integración de APIs REST y desarrollo de interfaces responsivas, accesibles y orientadas al rendimiento. Durante más de cinco años he participado en el desarrollo de más de 50 campañas y proyectos digitales para marcas de AB InBev, trabajando principalmente con React, Next.js y Drupal sobre Acquia. Cuento además con experiencia colaborando en equipos multidisciplinarios, participando en definición de arquitectura Frontend, estimación de tareas, revisión de código, creación de componentes reutilizables y mentoría de desarrolladores junior y practicantes. He trabajado en proyectos sobre Azure y AWS, incluyendo integración con AWS Cognito, además de entornos de desarrollo basados en Docker y flujos CI/CD gestionados por equipos de infraestructura.",
  careerFocus: "Frontend Development",
  yearsOfExperience: 5,
  coreCompetencies: [
    "Frontend Development",
    "React Development",
    "Next.js Development",
    "TypeScript",
    "JavaScript",
    "Frontend Architecture",
    "Component Design Systems",
    "Reusable Components",
    "Responsive Web Design",
    "Web Accessibility",
    "Performance Optimization",
    "REST API Integration",
    "State Management",
    "Mobile Development",
    "Code Review",
    "Technical Estimation",
    "Technical Mentoring",
  ],
  technicalSkills: {
    languages: ["JavaScript ES6+", "TypeScript", "HTML5", "CSS3", "Sass"],
    frontend: [
      "React",
      "Next.js",
      "React Router",
      "React Hook Form",
      "TanStack Query (React Query)",
      "TanStack Table",
      "Axios",
      "Zod",
      "Vite",
      "Tailwind CSS",
      "CSS Modules",
      "shadcn/ui",
      "Framer Motion",
      "Swiper.js",
      "Responsive Design",
      "Web Accessibility",
      "WCAG",
      "Performance Optimization",
      "Web Animations",
    ],
    stateManagement: ["Zustand", "Redux Toolkit", "React Context"],
    mobile: ["React Native", "Expo"],
    backend: [
      "Node.js",
      "REST APIs",
      "API Integration",
      "Basic API Development",
      "Frontend-Backend Integration",
    ],
    cms: ["Drupal", "Drupal Themes", "Acquia", "Shopify Themes"],
    testing: ["Vitest", "Jest", "React Testing Library"],
    cloud: ["Microsoft Azure", "Azure DevOps", "AWS", "AWS Cognito"],
    devopsAndInfrastructure: [
      "Docker",
      "Docker Compose",
      "GitHub Actions",
      "CI/CD",
      "Nginx",
    ],
    versionControl: ["Git", "GitHub"],
    tools: [
      "Visual Studio Code",
      "Postman",
      "Figma",
      "Trello",
      "Notion",
    ],
    aiAndDeveloperProductivity: [
      "Cursor",
      "ChatGPT",
      "Google Gemini",
      "Claude",
    ],
    databasesKnowledge: ["MySQL", "MongoDB", "Supabase"],
  },
  experience: [
    {
      title: "Desarrollador Frontend",
      company: "150 Porciento SAS",
      location: "Atlántico, Colombia",
      start: "2019",
      end: "Present",
      durationLabel: "5+ años",
      employmentType: "Tiempo completo",
      summary:
        "Desarrollo de aplicaciones web y plataformas digitales para diferentes clientes y marcas, con especial participación en proyectos y campañas digitales para AB InBev. Trabajo principalmente con React, Next.js, TypeScript, JavaScript y Drupal, colaborando con equipos de Backend, diseño e infraestructura.",
      responsibilities: [
        "Desarrollo y mantenimiento de aplicaciones web utilizando React, Next.js, TypeScript y JavaScript.",
        "Participación durante más de cinco años en el desarrollo y mantenimiento de más de 50 campañas y proyectos digitales para marcas de AB InBev.",
        "Desarrollo de proyectos utilizando Drupal y Acquia, incluyendo personalización y desarrollo de temas Frontend.",
        "Creación de interfaces responsivas y componentes reutilizables utilizando tecnologías como Tailwind CSS, Sass, CSS Modules y shadcn/ui.",
        "Gestión de estado de aplicaciones utilizando Zustand, Redux Toolkit y React Context.",
        "Gestión y sincronización de datos del servidor mediante TanStack Query (React Query).",
        "Integración de aplicaciones Frontend con servicios Backend mediante APIs REST.",
        "Desarrollo de aplicaciones móviles utilizando React Native y Expo.",
        "Participación en la definición de arquitecturas Frontend y decisiones técnicas relacionadas con la organización y reutilización de componentes.",
        "Creación de componentes reutilizables para mantener consistencia y facilitar la evolución de las aplicaciones.",
        "Participación en estimación de esfuerzo y horas de desarrollo para funcionalidades y tareas técnicas.",
        "Realización de revisiones de código para mantener estándares de calidad y buenas prácticas.",
        "Mentoría y acompañamiento técnico a desarrolladores junior y practicantes.",
        "Desarrollo de interfaces considerando criterios de accesibilidad y buenas prácticas relacionadas con WCAG.",
        "Optimización de rendimiento y experiencia de usuario en aplicaciones web.",
        "Desarrollo y ejecución de pruebas utilizando Vitest, Jest y React Testing Library.",
        "Trabajo diario con entornos de desarrollo basados en Docker y Docker Compose.",
        "Creación y modificación de Dockerfiles básicos para proyectos Frontend.",
        "Trabajo en proyectos alojados sobre Azure, utilizando repositorios, herramientas de colaboración y servicios de integración y despliegue proporcionados por los equipos de infraestructura.",
        "Participación en flujos de trabajo con CI/CD y pipelines gestionados por equipos de Backend o infraestructura.",
        "Trabajo en proyectos sobre AWS e integración de aplicaciones con servicios como AWS Cognito.",
        "Colaboración con equipos multidisciplinarios bajo metodologías ágiles.",
        "Uso de Figma para interpretación de diseños, revisión de interfaces, extracción de recursos gráficos, ajustes de copys y modificaciones menores necesarias durante la implementación.",
      ],
      technicalLeadership: [
        "Code Review",
        "Mentoría de desarrolladores junior y practicantes",
        "Estimación de tareas y esfuerzo técnico",
        "Participación en definición de arquitectura Frontend",
        "Diseño de componentes reutilizables",
        "Colaboración técnica con equipos Backend, diseño e infraestructura",
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "JavaScript",
        "React Native",
        "Expo",
        "Zustand",
        "Redux Toolkit",
        "React Context",
        "TanStack Query",
        "React Router",
        "React Hook Form",
        "Tailwind CSS",
        "Sass",
        "CSS Modules",
        "shadcn/ui",
        "Vite",
        "Drupal",
        "Acquia",
        "Shopify",
        "REST APIs",
        "Docker",
        "Docker Compose",
        "Azure",
        "Azure DevOps",
        "AWS",
        "AWS Cognito",
        "Vitest",
        "Jest",
        "React Testing Library",
        "Git",
        "GitHub",
      ],
    },
    {
      title:
        "Tecnólogo en Administración del Ensamble y Mantenimiento de Computadores",
      company: "Empresa del sector de logística y tecnología",
      location: "Atlántico, Colombia",
      start: "2013",
      end: "2019",
      durationLabel: "6 años",
      employmentType: "Tiempo completo",
      summary: "",
      responsibilities: [
        "Gestión operativa y mantenimiento preventivo y correctivo de infraestructura tecnológica.",
        "Gestión logística e inventario de equipos tecnológicos.",
        "Elaboración de documentación técnica y procesos estructurados.",
        "Resolución de problemas técnicos y atención de requerimientos operativos.",
        "Desarrollo de habilidades de organización, análisis y trabajo en equipo.",
        "Fortalecimiento de la lógica de programación y fundamentos técnicos que posteriormente facilitaron la transición hacia el desarrollo de software.",
      ],
      technicalLeadership: [],
      technologies: [],
    },
  ],
  featuredProjects: [
    {
      name: "AB InBev / Bavaria - Campañas y Plataformas Digitales",
      role: "Desarrollador Frontend",
      description:
        "Participación durante más de cinco años en el desarrollo y mantenimiento de más de 50 campañas y proyectos digitales para marcas de AB InBev. Trabajo en proyectos de diferentes duraciones y alcances, incluyendo campañas de aproximadamente 15 días y proyectos de mayor duración.",
      highlights: [
        "Desarrollo de interfaces y funcionalidades Frontend.",
        "Participación en proyectos desarrollados con React y Next.js.",
        "Desarrollo y personalización de temas para Drupal sobre Acquia.",
        "Trabajo en equipos multidisciplinarios con Backend, diseño e infraestructura.",
        "Participación en proyectos con altos requerimientos de rendimiento y experiencia de usuario.",
      ],
      technologies: [
        "React",
        "Next.js",
        "TypeScript",
        "JavaScript",
        "Drupal",
        "Acquia",
        "Docker",
        "Azure",
      ],
      status: "",
    },
    {
      name: "Cine sin Barreras",
      role: "Desarrollador Frontend",
      description:
        "Desarrollo de una aplicación orientada a mejorar la accesibilidad y experiencia de personas con discapacidad visual y auditiva.",
      highlights: [
        "Desarrollo de interfaces orientadas a accesibilidad.",
        "Participación en la implementación de funcionalidades relacionadas con audiodescripción, subtítulos y lenguaje de señas.",
        "Trabajo con requerimientos de sincronización de contenido y experiencia de usuario.",
      ],
      technologies: ["React", "JavaScript", "Web Accessibility", "WCAG"],
      status:
        "Requiere validación de tecnologías y alcance exacto antes de publicar en CV.",
    },
    {
      name: "Plataformas Educativas - Universidad de Cundinamarca",
      role: "Desarrollador Frontend",
      description:
        "Participación en el desarrollo de interfaces y componentes para plataformas educativas.",
      highlights: [
        "Desarrollo de interfaces responsivas.",
        "Creación de componentes reutilizables.",
        "Implementación de buenas prácticas de accesibilidad y experiencia de usuario.",
        "Colaboración en la evolución de plataformas digitales.",
      ],
      technologies: ["React", "JavaScript", "CSS", "Responsive Design"],
      status:
        "Requiere validación de tecnologías y alcance exacto antes de publicar en CV.",
    },
    {
      name: "Drupal y Shopify - Temas Personalizados",
      role: "Desarrollador Frontend",
      description:
        "Desarrollo y personalización de temas Frontend para plataformas basadas en Drupal y Shopify.",
      highlights: [
        "Desarrollo y personalización de temas.",
        "Integración de interfaces con servicios y APIs.",
        "Implementación de diseños responsivos.",
        "Mantenimiento y evolución de plataformas existentes.",
      ],
      technologies: [
        "Drupal",
        "Acquia",
        "Shopify",
        "JavaScript",
        "HTML5",
        "CSS3",
        "Sass",
      ],
      status: "",
    },
  ],
  leadershipAndCollaboration: [
    "Participación en definición de arquitecturas Frontend.",
    "Participación en estimación de esfuerzo y horas de desarrollo.",
    "Revisión de código de compañeros y validación de buenas prácticas.",
    "Mentoría y acompañamiento técnico de desarrolladores junior y practicantes.",
    "Diseño y creación de componentes reutilizables.",
    "Colaboración con equipos Backend para integración de APIs y servicios.",
    "Colaboración con equipos de infraestructura en proyectos con Azure, AWS, Docker y CI/CD.",
    "Trabajo bajo metodologías ágiles y dinámicas de equipos multidisciplinarios.",
  ],
  cloudAndInfrastructureExperience: {
    azure: {
      level: "Experiencia de trabajo",
      description:
        "Experiencia trabajando en proyectos cuya infraestructura y plataforma principal se encontraba en Azure. Uso de repositorios, colaboración con equipos y consumo de servicios relacionados con integración y pipelines administrados por equipos de infraestructura.",
      implementationLevel:
        "No responsable principal de configuración de infraestructura o pipelines.",
    },
    aws: {
      level: "Experiencia de integración",
      description:
        "Participación en proyectos alojados sobre AWS e integración de aplicaciones con AWS Cognito.",
      implementationLevel:
        "Experiencia principalmente desde el Frontend y la integración de servicios.",
    },
    docker: {
      level: "Experiencia práctica",
      description:
        "Trabajo diario en proyectos desarrollados y ejecutados en entornos Dockerizados. Creación de Dockerfiles básicos para algunos proyectos Frontend y uso de Docker Compose para entornos locales.",
      implementationLevel: "Intermedio básico desde el enfoque Frontend.",
    },
    ciCd: {
      level: "Experiencia como colaborador",
      description:
        "Experiencia trabajando dentro de flujos CI/CD y pipelines administrados principalmente por equipos Backend o infraestructura.",
      implementationLevel:
        "Usuario y colaborador del flujo; no responsable principal de implementación de pipelines.",
    },
    githubActions: {
      level: "Experiencia de trabajo",
      description:
        "Experiencia trabajando en proyectos que utilizan GitHub Actions dentro de los flujos de CI/CD.",
      implementationLevel:
        "No responsable principal de creación o administración de workflows.",
    },
    nginx: {
      level: "Conocimiento complementario",
      description:
        "Conocimiento y exposición a Nginx dentro de entornos de desarrollo y despliegue.",
      implementationLevel:
        "No responsable principal de configuración de infraestructura.",
    },
  },
  aiAndDeveloperProductivity: {
    primaryTools: ["Cursor", "ChatGPT", "Google Gemini"],
    secondaryExperience: ["Claude", "Codex"],
    description:
      "Uso frecuente de herramientas de inteligencia artificial como apoyo diario al desarrollo de software, investigación técnica, consulta de documentación, análisis de problemas, exploración de soluciones y aceleración del flujo de trabajo.",
    usageAreas: [
      "Investigación técnica",
      "Resolución de problemas",
      "Consulta de documentación",
      "Generación y revisión de código",
      "Exploración de arquitecturas",
      "Refactorización",
      "Optimización del flujo de desarrollo",
    ],
  },
  designAndProductCollaboration: {
    tools: ["Figma", "Trello", "Notion", "Postman"],
    activities: [
      "Interpretación de diseños UI.",
      "Revisión y análisis de layouts.",
      "Extracción y preparación de recursos gráficos.",
      "Edición de copys y contenido visual.",
      "Realización de ajustes menores sobre archivos de diseño.",
      "Colaboración con equipos de diseño durante la implementación.",
    ],
  },
  databasesAndBackendLearning: {
    professionalExperience:
      "No he sido responsable principal de lógica de negocio, persistencia de datos o administración de bases de datos en producción. Estas responsabilidades fueron gestionadas principalmente por equipos Backend.",
    backendExperience: [
      "Consumo de APIs REST.",
      "Integración Frontend-Backend.",
      "Creación de APIs simples con Node.js para pruebas y necesidades de desarrollo.",
      "Conocimiento básico del ecosistema Node.js.",
    ],
    academicAndSelfLearning: ["MySQL", "MongoDB", "Supabase"],
  },
  education: [
    {
      title:
        "Tecnólogo en Administración del Ensamble y Mantenimiento de Computadores",
      institution: "Servicio Nacional de Aprendizaje (SENA)",
      type: "Tecnólogo",
      status: "Completado",
      detail: "",
    },
    {
      title: "Formación en Desarrollo Web y Arquitectura Frontend",
      institution: "Platzi",
      type: "Cursos y formación complementaria",
      status: "",
      detail:
        "Formación continua en React, Next.js, TypeScript, JavaScript, desarrollo web y arquitectura Frontend.",
    },
  ],
  languages: [
    { name: "Español", level: "Nativo", status: "" },
    {
      name: "Inglés",
      level: "A1",
      status: "En proceso de mejora",
    },
  ],
  methodologies: ["Agile", "Scrum"],
  softSkills: [
    "Resolución de problemas",
    "Trabajo en equipo",
    "Comunicación técnica",
    "Mentoría",
    "Aprendizaje continuo",
    "Adaptabilidad",
    "Organización",
    "Atención al detalle",
  ],
  careerPositioning: {
    primary: "Frontend Developer",
    targetRoles: [
      "Frontend Developer",
      "Frontend Engineer",
      "React Developer",
      "React / Next.js Developer",
      "Senior Frontend Developer",
    ],
    secondary: [
      "Full Stack Developer con enfoque Frontend",
      "React Native Developer",
    ],
    recommendedHeadline: "Frontend Developer | React | Next.js | TypeScript",
  },
  atsKeywords: [
    "Frontend Developer",
    "Frontend Engineer",
    "React",
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "Sass",
    "Tailwind CSS",
    "CSS Modules",
    "shadcn/ui",
    "React Router",
    "React Hook Form",
    "TanStack Query",
    "React Query",
    "TanStack Table",
    "Zustand",
    "Redux Toolkit",
    "React Context",
    "React Native",
    "Expo",
    "Node.js",
    "REST API",
    "Drupal",
    "Acquia",
    "Shopify",
    "Docker",
    "Docker Compose",
    "AWS",
    "AWS Cognito",
    "Azure",
    "Azure DevOps",
    "GitHub Actions",
    "CI/CD",
    "Git",
    "GitHub",
    "Vitest",
    "Jest",
    "React Testing Library",
    "WCAG",
    "Web Accessibility",
    "Responsive Design",
    "Performance Optimization",
    "Frontend Architecture",
    "Code Review",
    "Technical Mentoring",
    "Agile",
    "Scrum",
  ],
  cvNotes: {
    positioning:
      "El perfil debe posicionarse principalmente como Frontend Developer con experiencia sólida en React, Next.js y TypeScript. No se recomienda utilizar Full Stack Junior como titular.",
    accuracy: [
      "No presentar CI/CD, GitHub Actions, Nginx o Azure como habilidades avanzadas de implementación de infraestructura.",
      "No presentar AWS como experiencia de administración de infraestructura; destacar integración con AWS Cognito.",
      "No presentar Docker como experiencia DevOps avanzada; destacar trabajo diario con proyectos Dockerizados y creación de Dockerfiles básicos.",
      "No presentar Node.js como Backend avanzado; destacar consumo de APIs y creación de APIs simples para pruebas.",
      "No presentar MySQL, MongoDB o Supabase como experiencia profesional de producción; clasificarlos como conocimientos complementarios.",
      "No presentar React Query como herramienta de estado global; clasificarlo como gestión y sincronización de estado del servidor.",
      "Utilizar Redux Toolkit en lugar de Redux genérico.",
      "Incluir React Context como tecnología de gestión de estado.",
      "Destacar más de 50 campañas o proyectos para AB InBev como uno de los principales diferenciadores profesionales.",
    ],
    missingDataToValidateBeforeFinalCV: [
      "Confirmar tecnologías exactas utilizadas en el proyecto Cine sin Barreras.",
      "Confirmar tecnologías exactas utilizadas en los proyectos de la Universidad de Cundinamarca.",
      "Confirmar si los más de 50 proyectos para AB InBev pueden mencionarse públicamente en un CV.",
      "Confirmar nombre exacto y URL pública del portafolio.",
      "Confirmar URL pública de LinkedIn.",
      "Confirmar URL pública de GitHub.",
      "Confirmar nivel real de lectura, escritura y conversación en inglés.",
      "Confirmar si se han utilizado React Server Components, Next.js App Router, Suspense, lazy loading o code splitting en proyectos profesionales.",
      "Confirmar si existe experiencia profesional con Playwright, Cypress u otras herramientas de testing además de Jest, Vitest y React Testing Library.",
    ],
  },
};
